// Isadora Moon 단어장 데이터
// 각 항목: chapter(챕터), word(단어/표현), pos(품사), meaning(뜻), example(본문 예문)
const VOCAB_DATA = [
  // ===== Chapter One =====
  { chapter: "Chapter One", word: "lovely", pos: "형용사", meaning: "사랑스러운, 즐거운, 멋진", example: "I was having a lovely time at my best friend Zoe's house." },
  { chapter: "Chapter One", word: "favourite", pos: "형용사", meaning: "가장 좋아하는", example: "Pink Rabbit used to be my favourite cuddly toy," },
  { chapter: "Chapter One", word: "cuddly toy", pos: "명사(구)", meaning: "안고 노는 봉제 인형", example: "Pink Rabbit used to be my favourite cuddly toy" },
  { chapter: "Chapter One", word: "magicked ~ alive", pos: "동사(구)", meaning: "마법을 부려 ~을 살아 있게 만들다", example: "my mum magicked him alive with her wand." },
  { chapter: "Chapter One", word: "wand", pos: "명사", meaning: "(마법) 지팡이", example: "my mum magicked him alive with her wand." },
  { chapter: "Chapter One", word: "daisy chain", pos: "명사(구)", meaning: "데이지꽃을 엮어 만든 목걸이(화환)", example: "Zoe and I were sitting in her back garden making daisy chains" },
  { chapter: "Chapter One", word: "sleepover", pos: "명사", meaning: "(친구 집에서) 자고 노는 파자마 파티", example: "when we were having a sleepover." },
  { chapter: "Chapter One", word: "dressing-up box", pos: "명사(구)", meaning: "옷 갈아입기 놀이 상자 (코스튬 상자)", example: "she has the best dressing-up box of anyone I know!" },
  { chapter: "Chapter One", word: "fairy cakes", pos: "명사(구)", meaning: "(영국식) 작은 컵케이크", example: "we had baked fairy cakes," },
  { chapter: "Chapter One", word: "changing shape", pos: "동사(구)", meaning: "모양이 바뀌다, 변하다", example: "we watched the white fluffy clouds changing shape." },
  { chapter: "Chapter One", word: "uncertainly", pos: "부사", meaning: "확신 없이, 머뭇거리며", example: "'Cycling?' I said uncertainly." },
  { chapter: "Chapter One", word: "reluctantly", pos: "부사", meaning: "마지못해, 내키지 않아 하며", example: "said Zoe, reluctantly." },
  { chapter: "Chapter One", word: "lean up against", pos: "동사(구)", meaning: "~에 기대어 세워져 있다", example: "Leaning up against the wall were some bicycles." },
  { chapter: "Chapter One", word: "handlebars", pos: "명사", meaning: "(자전거의) 손잡이", example: "Shiny streamers hung down from the handlebars" },
  { chapter: "Chapter One", word: "seeing as", pos: "접속사(숙어)", meaning: "~이니까, ~인 만큼(= since, because)", example: "You can ride my new one, seeing as you're the guest," },
  { chapter: "Chapter One", word: "it seems a shame", pos: "관용구", meaning: "아쉬운 일인 것 같다, 안타깝다", example: "it seems a shame for anyone to ride it." },
  { chapter: "Chapter One", word: "catch up with", pos: "동사(구,숙어)", meaning: "(놓친 것을) 나중에 따라잡다, 이어서 보다", example: "We can catch up with Sponge and Sprinkles later!" },
  { chapter: "Chapter One", word: "in dismay", pos: "관용구", meaning: "당황하여, 낙담하여", example: "I watched in dismay as Zoe walked her bike out of the garage" },
  { chapter: "Chapter One", word: "hop onto", pos: "동사(구)", meaning: "폴짝 뛰어 올라타다", example: "then hopped onto it, doing a loop of the driveway." },
  { chapter: "Chapter One", word: "driveway", pos: "명사", meaning: "(집 앞) 차량 진입로", example: "doing a loop of the driveway." },
  { chapter: "Chapter One", word: "swirly", pos: "형용사", meaning: "소용돌이치는 듯한, 울렁거리는", example: "My tummy felt all swirly." },
  { chapter: "Chapter One", word: "disappointed", pos: "형용사", meaning: "실망한", example: "Zoe cycled back towards me, looking disappointed." },
  { chapter: "Chapter One", word: "a knot of anxiety", pos: "관용구", meaning: "(속이 꽉 조이는 듯한) 불안감", example: "There was a knot of anxiety in my stomach" },
  { chapter: "Chapter One", word: "distracted", pos: "형용사(분사)", meaning: "정신이 팔린, 주의가 흐트러진", example: "I had been so distracted by the TV show" },
  { chapter: "Chapter One", word: "shrugged", pos: "동사", meaning: "어깨를 으쓱했다", example: "I shrugged." },
  { chapter: "Chapter One", word: "flap into the air", pos: "동사(구)", meaning: "(날개를) 퍼덕이며 날아오르다", example: "together we flapped into the air, rising up above the houses" },
  { chapter: "Chapter One", word: "glinted", pos: "동사", meaning: "반짝였다, 빛났다", example: "golden light glinted off the pond in the park down below." },
  { chapter: "Chapter One", word: "gasped", pos: "동사", meaning: "(놀라거나 감탄하여) 숨을 헉 들이쉬며 말했다", example: "'Beautiful!' gasped Mum." },

  // ===== Chapter Two =====
  { chapter: "Chapter Two", word: "couldn't help ~ing", pos: "숙어", meaning: "~하지 않을 수 없었다", example: "I couldn't help thinking about the pizza I was missing out on." },
  { chapter: "Chapter Two", word: "miss out on", pos: "동사(구)", meaning: "(좋은 것을) 놓치다", example: "the pizza I was missing out on." },
  { chapter: "Chapter Two", word: "feel bad for", pos: "숙어", meaning: "~에게 미안한 마음이 들다", example: "I felt bad for Zoe too." },
  { chapter: "Chapter Two", word: "admit", pos: "동사", meaning: "인정하다, 시인하다", example: "'A little bit,' I admitted." },
  { chapter: "Chapter Two", word: "mind", pos: "동사", meaning: "꺼리다, 싫어하다", example: "I thought you didn't mind them in pasta sauce." },
  { chapter: "Chapter Two", word: "nervous", pos: "형용사", meaning: "긴장한, 불안한", example: "the thought of getting onto a bike made me feel so nervous" },
  { chapter: "Chapter Two", word: "fall off", pos: "동사(구)", meaning: "(탈것에서) 떨어지다", example: "I know I'd just fall off it and hurt myself." },
  { chapter: "Chapter Two", word: "as though", pos: "접속사(숙어)", meaning: "마치 ~인 것처럼", example: "said Mum as though she understood." },
  { chapter: "Chapter Two", word: "confused", pos: "형용사", meaning: "혼란스러운, 헷갈리는", example: "Dad just looked confused." },
  { chapter: "Chapter Two", word: "contraption", pos: "명사", meaning: "(괴상하게 생긴) 기계, 장치", example: "Funny-looking contraptions if you ask me." },
  { chapter: "Chapter Two", word: "shoot a pointed look", pos: "관용구", meaning: "따끔한(의미심장한) 눈빛을 보내다", example: "Mum shot him a pointed look." },
  { chapter: "Chapter Two", word: "join in with", pos: "동사(구)", meaning: "~와 함께 어울리다, 참여하다", example: "you can join in with your friends!" },
  { chapter: "Chapter Two", word: "pop back", pos: "동사(구)", meaning: "잠깐 다시 들르다", example: "why don't we pop back to Zoe's house after dinner" },
  { chapter: "Chapter Two", word: "doorstep", pos: "명사", meaning: "현관 계단", example: "I stood on Zoe's doorstep after ringing the bell." },
  { chapter: "Chapter Two", word: "mumble", pos: "동사", meaning: "중얼거리듯 말하다", example: "I mumbled." },
  { chapter: "Chapter Two", word: "rush over", pos: "동사(구)", meaning: "서둘러 다가오다", example: "yelled Zoe, rushing over to me for a hug." },
  { chapter: "Chapter Two", word: "baffled", pos: "형용사", meaning: "어리둥절한, 당황한", example: "Zoe stared at me with a baffled look on her face." },
  { chapter: "Chapter Two", word: "burst out laughing", pos: "관용구", meaning: "웃음을 터뜨리다", example: "Then she burst out laughing." },
  { chapter: "Chapter Two", word: "embarrassed", pos: "형용사", meaning: "창피한, 쑥스러운", example: "I felt really embarrassed about it." },
  { chapter: "Chapter Two", word: "have a point", pos: "관용구", meaning: "일리가 있다, 맞는 말을 하다", example: "She had a point!" },
  { chapter: "Chapter Two", word: "feel lighter", pos: "관용구", meaning: "(마음이) 홀가분해지다", example: "I felt so much lighter now that I had opened up." },
  { chapter: "Chapter Two", word: "open up", pos: "동사(구)", meaning: "마음을 털어놓다", example: "now that I had opened up." },
  { chapter: "Chapter Two", word: "in the first place", pos: "숙어", meaning: "애당초, 애초부터", example: "to my best friend in the first place!" },
  { chapter: "Chapter Two", word: "perk up", pos: "동사(구)", meaning: "활기를 되찾다, 기운이 나다", example: "'Oh OK!' said Zoe, perking up again." },
  { chapter: "Chapter Two", word: "glance", pos: "동사", meaning: "흘낏 보다", example: "said her dad, glancing out of the window." },
  { chapter: "Chapter Two", word: "firmly", pos: "부사", meaning: "단호하게", example: "said Zoe's dad, firmly." },
  { chapter: "Chapter Two", word: "practise", pos: "동사", meaning: "연습하다(영국식 철자)", example: "she could practise at home." },
  { chapter: "Chapter Two", word: "get on with it", pos: "숙어", meaning: "(하던 것을) 계속 잘 해나가다", example: "to see how she's getting on with it?" },

  // ===== Chapter Two~Three =====
  { chapter: "Chapter Two~Three", word: "grippy tabs", pos: "명사(구)", meaning: "미끄럼 방지 벨크로 탭", example: "pads around my legs and arms with the grippy tabs." },
  { chapter: "Chapter Two~Three", word: "extra safe", pos: "표현", meaning: "더욱 안전한", example: "'Better to be extra safe!'" },
  { chapter: "Chapter Two~Three", word: "topple sideways", pos: "동사(구)", meaning: "옆으로 넘어지다, 쓰러지다", example: "for a few metres down... before toppling sideways" },
  { chapter: "Chapter Two~Three", word: "land with a crash", pos: "동사(구)", meaning: "쿵 소리를 내며 넘어지다", example: "landing with a crash on the grass." },
  { chapter: "Chapter Two~Three", word: "wobble", pos: "동사", meaning: "휘청거리다, 흔들리다", example: "wobble... wobble..." },
  { chapter: "Chapter Two~Three", word: "scrabble to find", pos: "동사(구)", meaning: "허둥지둥 더듬어 찾다", example: "scrabbled to find the pedals." },
  { chapter: "Chapter Two~Three", word: "perch on", pos: "동사(구)", meaning: "(불안정하게) 걸터앉다", example: "I continued to perch on the bike saddle" },
  { chapter: "Chapter Two~Three", word: "flail around", pos: "동사(구)", meaning: "마구 허우적거리다", example: "I flailed around for them with my feet" },
  { chapter: "Chapter Two~Three", word: "stricken", pos: "형용사", meaning: "망연자실한, 어쩔 줄 모르는", example: "Mum looked a bit stricken." },
  { chapter: "Chapter Two~Three", word: "chip in", pos: "동사(구)", meaning: "(대화에) 끼어들다, 거들다", example: "'I agree with Isadora!' Dad chipped in." },
  { chapter: "Chapter Two~Three", word: "get the hang of it", pos: "숙어", meaning: "요령을 터득하다", example: "I'm sure I'll get the hang of it soon!" },
  { chapter: "Chapter Two~Three", word: "with a huff", pos: "관용구", meaning: "씩씩거리며, 부루퉁해서", example: "With a huff, I lifted the bike back up" },
  { chapter: "Chapter Two~Three", word: "deckchair", pos: "명사", meaning: "접이식 안락의자", example: "Dad went back to his deckchair" },
  { chapter: "Chapter Two~Three", word: "have a snooze", pos: "동사(구)", meaning: "잠깐 눈을 붙이다, 낮잠 자다", example: "under the parasol for a snooze" },
  { chapter: "Chapter Two~Three", word: "freewheel", pos: "동사", meaning: "페달을 밟지 않고 나아가다", example: "We could freewheel down the big hill in the park" },
  { chapter: "Chapter Two~Three", word: "a fluttery feeling", pos: "관용구", meaning: "두근두근한 느낌", example: "with a fluttery feeling inside my tummy." },
  { chapter: "Chapter Two~Three", word: "half excited, half nervous", pos: "표현", meaning: "반은 설레고 반은 긴장한", example: "I felt half excited, half nervous" },
  { chapter: "Chapter Two~Three", word: "gobble down", pos: "동사(구)", meaning: "허겁지겁 먹어 치우다", example: "I gobbled it down." },
  { chapter: "Chapter Two~Three", word: "porridge", pos: "명사", meaning: "오트밀 죽", example: "she pushed a bowl of porridge towards me" },
  { chapter: "Chapter Two~Three", word: "visions of", pos: "관용구", meaning: "~에 대한 상상(장면)", example: "Visions of the lovely things I would be able to do" },
  { chapter: "Chapter Two~Three", word: "crossbar", pos: "명사", meaning: "(자전거) 크로스바(가로대)", example: "I swung my leg over the crossbar" },
  { chapter: "Chapter Two~Three", word: "stay upright", pos: "동사(구)", meaning: "똑바로 서다, 균형을 유지하다", example: "It was just staying upright in one place!" },
  { chapter: "Chapter Two~Three", word: "flap", pos: "동사", meaning: "(날개를) 퍼덕이다", example: "and flap, flap, flap my wings." },
  { chapter: "Chapter Two~Three", word: "wheel out", pos: "동사(구)", meaning: "(자전거 등을) 밀고 나오다", example: "wheeling it out of her special fairy greenhouse" },
  { chapter: "Chapter Two~Three", word: "secure the clip", pos: "동사(구)", meaning: "(잠금) 클립을 채우다", example: "she secured the clip shut under my chin." },

  // ===== Chapter Three~Four =====
  { chapter: "Chapter Three~Four", word: "yelp", pos: "동사", meaning: "(놀라거나 아파서) 소리지르다", example: "'Oh no!' I yelped as the bike lifted me" },
  { chapter: "Chapter Three~Four", word: "hover", pos: "동사", meaning: "공중에서 맴돌다, 정지비행하다", example: "we were hovering above the garden" },
  { chapter: "Chapter Three~Four", word: "tug", pos: "동사", meaning: "잡아당기다", example: "I could tug it back down to the garden?" },
  { chapter: "Chapter Three~Four", word: "weave", pos: "동사", meaning: "이리저리 피해 나아가다", example: "the bike weaved round trees and bushes" },
  { chapter: "Chapter Three~Four", word: "grip tightly", pos: "동사(구)", meaning: "꽉 움켜쥐다", example: "gripping tightly onto the handlebars" },
  { chapter: "Chapter Three~Four", word: "narrowly avoid", pos: "동사(구)", meaning: "아슬아슬하게 피하다", example: "narrowly avoiding the pond." },
  { chapter: "Chapter Three~Four", word: "out of control", pos: "관용구", meaning: "통제 불능의", example: "Was it supposed to feel so fast and out of control?" },
  { chapter: "Chapter Three~Four", word: "zoom", pos: "동사", meaning: "쌩 하고 질주하다", example: "I zoomed as the pedals spun on their own" },
  { chapter: "Chapter Three~Four", word: "exhausted", pos: "형용사", meaning: "기진맥진한, 매우 지친", example: "My legs were starting to feel exhausted!" },
  { chapter: "Chapter Three~Four", word: "alarming speed", pos: "관용구", meaning: "놀랄 만큼 위험한 속도", example: "the wheels whizzing round at an alarming speed." },
  { chapter: "Chapter Three~Four", word: "splosh", pos: "동사(의성어)", meaning: "첨벙 소리를 내다", example: "we were about to SPLOSH right into the pond" },
  { chapter: "Chapter Three~Four", word: "soar upwards", pos: "동사(구)", meaning: "위로 솟구쳐 오르다", example: "the bike began to soar upwards." },
  { chapter: "Chapter Three~Four", word: "despondently", pos: "부사", meaning: "낙담하여, 풀이 죽어서", example: "I replied despondently." },
  { chapter: "Chapter Three~Four", word: "sprinkle", pos: "동사", meaning: "흩뿌리다", example: "sprinkling another shower of twinkling stars" },
  { chapter: "Chapter Three~Four", word: "confidently", pos: "부사", meaning: "자신 있게", example: "I confidently swung my leg over the crossbar" },
  { chapter: "Chapter Three~Four", word: "barely", pos: "부사", meaning: "거의 ~아니게, 겨우", example: "I had barely had time to get comfortable" },
  { chapter: "Chapter Three~Four", word: "whirr", pos: "동사(의성어)", meaning: "윙윙 소리를 내다", example: "whirr around with my feet on them." },
  { chapter: "Chapter Three~Four", word: "yell", pos: "동사", meaning: "소리치다, 외치다", example: "'DAD!' I yelled." },
  { chapter: "Chapter Three~Four", word: "angry tears", pos: "관용구", meaning: "분한(화난) 눈물", example: "as angry tears sprung to my eyes." },
  { chapter: "Chapter Three~Four", word: "spring to one's eyes", pos: "동사(구)", meaning: "(눈물이) 왈칵 솟다", example: "angry tears sprung to my eyes." },
  { chapter: "Chapter Three~Four", word: "scrape", pos: "명사", meaning: "긁힌 상처, 찰과상", example: "'It's just a little scrape,' she said" },
  { chapter: "Chapter Three~Four", word: "plaster", pos: "명사", meaning: "반창고(영국식 표현)", example: "Let's go and put a plaster on it." },
  { chapter: "Chapter Three~Four", word: "crosser voice", pos: "표현", meaning: "더 화가 난 목소리", example: "I said in a crosser voice than I meant to." },
  { chapter: "Chapter Three~Four", word: "stomp", pos: "동사", meaning: "쿵쿵거리며 걷다", example: "I stomped into the house and up the stairs." },
  { chapter: "Chapter Three~Four", word: "give up", pos: "동사(구)", meaning: "포기하다", example: "Maybe it was time to just give up!" },
  { chapter: "Chapter Three~Four", word: "do research on", pos: "동사(구)", meaning: "~에 대해 조사하다, 연구하다", example: "I'm going to do some research on cycling" },

  // ===== Chapter Five =====
  { chapter: "Chapter Five", word: "astonishment", pos: "명사", meaning: "놀람, 경악", example: "Zoe stared at me in astonishment." },
  { chapter: "Chapter Five", word: "doubtfully", pos: "부사", meaning: "미심쩍은 듯이, 의심스럽게", example: "'Really?' I said doubtfully." },
  { chapter: "Chapter Five", word: "envious", pos: "형용사", meaning: "부러워하는, 질투하는", example: "'I'm envious of your helmet!'" },
  { chapter: "Chapter Five", word: "wistfully", pos: "부사", meaning: "아쉬운 듯이, 그리운 듯이", example: "said Zoe wistfully." },
  { chapter: "Chapter Five", word: "clip on", pos: "동사(구)", meaning: "(헬멧 등을) 채우다", example: "As Zoe clipped her helmet on" },
  { chapter: "Chapter Five", word: "push off", pos: "동사(구)", meaning: "힘차게 밀어 출발하다", example: "before you push off, explained Zoe." },
  { chapter: "Chapter Five", word: "handbook", pos: "명사", meaning: "안내서, 소책자", example: "I remember from the cycling handbook" },
  { chapter: "Chapter Five", word: "instruct", pos: "동사", meaning: "지시하다, 알려주다", example: "instructed Zoe." },
  { chapter: "Chapter Five", word: "flutter", pos: "동사", meaning: "파닥거리다, 나부끼다", example: "fluttering up in the air on her fairy wings" },
  { chapter: "Chapter Five", word: "get used to", pos: "동사(구)", meaning: "~에 익숙해지다", example: "it gave me time to get used to pedalling" },
  { chapter: "Chapter Five", word: "whoop", pos: "동사", meaning: "환호성을 지르다", example: "whooped Zoe, clapping her hands excitedly" },
  { chapter: "Chapter Five", word: "positive", pos: "형용사", meaning: "긍정적인, 낙관적인", example: "I started to feel a bit more positive." },
  { chapter: "Chapter Five", word: "encouragingly", pos: "부사", meaning: "격려하듯이", example: "said Zoe, encouragingly." },
  { chapter: "Chapter Five", word: "in a panic", pos: "관용구", meaning: "당황하여, 허둥지둥", example: "I cried in a panic." },
  { chapter: "Chapter Five", word: "rescue", pos: "동사", meaning: "구하다, 구조하다", example: "there to rescue me, I fell" },
  { chapter: "Chapter Five", word: "insist", pos: "동사", meaning: "고집하다, 우기다", example: "I insisted, getting back onto the bike" },
  { chapter: "Chapter Five", word: "never mind", pos: "관용구", meaning: "신경 쓰지 마, 괜찮아", example: "'Never mind,' said Zoe." },
  { chapter: "Chapter Five", word: "clink", pos: "동사(의성어)", meaning: "쨍그랑 소리를 내다", example: "so that the ice cubes clinked." },
  { chapter: "Chapter Five", word: "motivated", pos: "형용사", meaning: "의욕이 있는, 동기부여가 된", example: "I didn't feel quite as motivated to practise" },
  { chapter: "Chapter Five", word: "messy eater", pos: "명사(구)", meaning: "지저분하게 먹는 사람", example: "Honeyblossom is a very messy eater!" },
  { chapter: "Chapter Five", word: "confidence", pos: "명사", meaning: "자신감", example: "my confidence had completely deserted me" },
  { chapter: "Chapter Five", word: "desert", pos: "동사", meaning: "저버리다, 떠나버리다", example: "It seemed as though my confidence had completely deserted me." },
  { chapter: "Chapter Five", word: "sigh", pos: "동사", meaning: "한숨 쉬다", example: "I sighed and gave up, putting the bike back" },
  { chapter: "Chapter Five", word: "sprout out", pos: "동사(구)", meaning: "(갑자기) 돋아나다, 솟아나다", example: "Little glittery butterfly wings sprouted out from it." },
  { chapter: "Chapter Five", word: "overnight", pos: "부사", meaning: "밤새, 하룻밤 동안", example: "where it had been kept safe overnight." },

  // ===== Chapter Five~Six =====
  { chapter: "Chapter Five~Six", word: "secretive", pos: "형용사", meaning: "비밀스러운", example: "Mum and Dad looked at each other with a secretive, sneaky expression" },
  { chapter: "Chapter Five~Six", word: "sneaky", pos: "형용사", meaning: "능글맞은, 짓궂은", example: "with a secretive, sneaky expression on their faces." },
  { chapter: "Chapter Five~Six", word: "ta-da", pos: "감탄사", meaning: "짜잔!", example: "'Ta-da!' said Mum, throwing open the door." },
  { chapter: "Chapter Five~Six", word: "throw open", pos: "동사(구)", meaning: "활짝 열다", example: "'Ta-da!' said Mum, throwing open the door." },
  { chapter: "Chapter Five~Six", word: "stack", pos: "동사", meaning: "쌓다, 쌓이다", example: "Stacked in front of the flower pots and gardening things" },
  { chapter: "Chapter Five~Six", word: "sleek", pos: "형용사", meaning: "매끈한, 세련된", example: "The other was sleek and black with bat wings" },
  { chapter: "Chapter Five~Six", word: "tassel", pos: "명사", meaning: "술 장식", example: "some black and pink tassels for the handlebars." },
  { chapter: "Chapter Five~Six", word: "bother ~ing", pos: "동사(구)", meaning: "굳이 ~하지 않다", example: "I didn't bother getting back onto the bike for a few days" },
  { chapter: "Chapter Five~Six", word: "a bit funny", pos: "표현", meaning: "좀 이상한, 어색한", example: "It felt a bit funny getting onto Zoe's old bike" },
  { chapter: "Chapter Five~Six", word: "suggest", pos: "동사", meaning: "제안하다", example: "'The pavement!' suggested Dad." },
  { chapter: "Chapter Five~Six", word: "shrug", pos: "동사", meaning: "어깨를 으쓱하다", example: "Dad shrugged." },
  { chapter: "Chapter Five~Six", word: "give it a go", pos: "숙어", meaning: "한번 해보다, 시도하다", example: "'Why don't we give it a go anyway?' he asked." },
  { chapter: "Chapter Five~Six", word: "keep going", pos: "동사(구)", meaning: "계속 나아가다", example: "I was able to keep going for ages and ages!" },
  { chapter: "Chapter Five~Six", word: "whip out", pos: "동사(구)", meaning: "휙 나부끼다, 휘날리다", example: "My hair whipped out behind me in the warm summer breeze" },
  { chapter: "Chapter Five~Six", word: "elation", pos: "명사", meaning: "벅찬 기쁨, 큰 환희", example: "the panic in my chest suddenly turning to elation." },
  { chapter: "Chapter Five~Six", word: "panic", pos: "명사", meaning: "당황, 공황", example: "I kept pedalling, the panic in my chest" },
  { chapter: "Chapter Five~Six", word: "let go", pos: "동사(구)", meaning: "손을 놓다", example: "I accidentally let go! You were going too fast!" },
  { chapter: "Chapter Five~Six", word: "pedal", pos: "동사", meaning: "페달을 밟다", example: "I was doing it! And Dad wasn't even having to hold onto me!" },
  { chapter: "Chapter Five~Six", word: "squeeze", pos: "동사", meaning: "꽉 쥐다", example: "'Squeeze the brake gently.'" },
  { chapter: "Chapter Five~Six", word: "hop off", pos: "동사(구)", meaning: "폴짝 내리다", example: "I managed to slow the bike down and stop it safely, hopping off." },
  { chapter: "Chapter Five~Six", word: "beam", pos: "동사", meaning: "활짝 웃다", example: "'Well done,' beamed Mum." },
  { chapter: "Chapter Five~Six", word: "grin", pos: "동사", meaning: "씩 웃다", example: "'You did!' agreed Dad, grinning widely" },
  { chapter: "Chapter Five~Six", word: "push down on", pos: "동사(구)", meaning: "(페달 등을) 밟아 누르다", example: "pushing down on the pedals" },
  { chapter: "Chapter Five~Six", word: "take a sharp turn", pos: "동사(구)", meaning: "급하게 방향을 틀다", example: "accidentally took a sharp turn—CRASH— right into a bush." },
  { chapter: "Chapter Five~Six", word: "mind", pos: "동사", meaning: "개의치 않다, 신경 쓰다", example: "It was just so lovely to be out all together, none of us minded." },
  { chapter: "Chapter Five~Six", word: "whoops", pos: "감탄사", meaning: "어이쿠, 이런(실수했을 때 하는 말)", example: "'Whoops!' I heard him say from inside the leaves." },
  { chapter: "Chapter Five~Six", word: "a little more practice", pos: "표현", meaning: "약간 더 연습이 필요함", example: "'I think I need a little more practice!'" },

  // ===== 부록: Top Tips for Cycling =====
  { chapter: "부록: Top Tips for Cycling", word: "helmet", pos: "명사", meaning: "헬멧", example: "Always wear a helmet." },
  { chapter: "부록: Top Tips for Cycling", word: "bright", pos: "형용사", meaning: "밝은, 선명한", example: "Wear bright clothes that are comfortable." },
  { chapter: "부록: Top Tips for Cycling", word: "comfortable", pos: "형용사", meaning: "편안한", example: "Wear bright clothes that are comfortable." },
  { chapter: "부록: Top Tips for Cycling", word: "be prepared for", pos: "동사(구)", meaning: "~에 대비하다", example: "Be prepared for all kinds of weather!" },
  { chapter: "부록: Top Tips for Cycling", word: "all kinds of", pos: "표현", meaning: "온갖 종류의", example: "Be prepared for all kinds of weather!" },
  { chapter: "부록: Top Tips for Cycling", word: "layer", pos: "명사", meaning: "겹쳐 입는 옷, 레이어", example: "It's good to wear layers in case you get too hot or cold" },
  { chapter: "부록: Top Tips for Cycling", word: "in case", pos: "접속사(숙어)", meaning: "~한 경우에 대비해서", example: "in case you get too hot or cold" },
  { chapter: "부록: Top Tips for Cycling", word: "waterproof", pos: "형용사", meaning: "방수의", example: "have a waterproof coat" },
  { chapter: "부록: Top Tips for Cycling", word: "stay dry", pos: "동사(구)", meaning: "젖지 않다, 마른 상태를 유지하다", example: "so you stay dry if it rains." },
  { chapter: "부록: Top Tips for Cycling", word: "extra comfort", pos: "표현", meaning: "더 큰 편안함", example: "You might like to wear gloves for extra comfort." },
  { chapter: "부록: Top Tips for Cycling", word: "grippy soles", pos: "명사(구)", meaning: "미끄럼 방지 밑창", example: "Wear shoes with grippy soles." },
];
