// Mirabelle in Double Trouble 단어장 데이터
// 각 항목: chapter(챕터), word(단어/표현), pos(품사), meaning(뜻), example(본문 예문)
// 아이가 책에 직접 밑줄 그은 단어·숙어·문장만 정리했습니다.
const MIRABELLE_VOCAB_DATA = [
  // ===== Chapter One =====
  { chapter: "Chapter One", word: "forgot", pos: "동사", meaning: "잊어버렸다", example: "'Er . . . I think I forgot,' I said." },
  { chapter: "Chapter One", word: "more often", pos: "부사(구)", meaning: "더 자주", example: "trying to get me to use my wand more often, but the truth is that I prefer to use witch magic like Mum!" },
  { chapter: "Chapter One", word: "witch", pos: "명사", meaning: "마녀", example: "the truth is that I prefer to use witch magic like Mum!" },
  { chapter: "Chapter One", word: "technically", pos: "부사", meaning: "엄밀히 말하면", example: "technically half fairy too, along with my brother, Wilbur." },
  { chapter: "Chapter One", word: "fetch", pos: "동사", meaning: "가지러 가다, 가져오다", example: "'There's still time to go and fetch it,' said Dad." },
  { chapter: "Chapter One", word: "glancing", pos: "동사", meaning: "흘깃 보다", example: "said Dad, glancing at his watch." },
  { chapter: "Chapter One", word: "while you're at it", pos: "관용구", meaning: "하는 김에", example: "'And while you're at it you can tell Mum to hurry up!'" },
  { chapter: "Chapter One", word: "own", pos: "동사", meaning: "소유하다", example: "My mum and dad own their own beauty business" },
  { chapter: "Chapter One", word: "beauty", pos: "명사", meaning: "아름다움", example: "own their own beauty business concocting organic face creams" },
  { chapter: "Chapter One", word: "concocting", pos: "동사", meaning: "(여러 재료를 섞어) 만들어내다", example: "business concocting organic face creams, perfumes, and lipsticks." },
  { chapter: "Chapter One", word: "turret", pos: "명사", meaning: "(작은) 탑", example: "Mum can spend all day up in her witch turret experimenting" },
  { chapter: "Chapter One", word: "ingredients", pos: "명사", meaning: "재료", example: "experimenting with ingredients and sometimes it's hard" },
  { chapter: "Chapter One", word: "tear her away from work", pos: "관용구", meaning: "그녀를 억지로 일에서 떼어놓다", example: "sometimes it's hard to tear her away from work!" },
  { chapter: "Chapter One", word: "fizzle", pos: "명사", meaning: "자글거리는 느낌, 짜릿함", example: "I felt a fizzle of excitement in my tummy." },
  { chapter: "Chapter One", word: "all-inclusive", pos: "형용사", meaning: "모든 것이 포함된", example: "at an all-inclusive witch resort in the mountains." },
  { chapter: "Chapter One", word: "cauldron", pos: "명사", meaning: "(마녀들이 쓰는) 가마솥", example: "to be a bubbling cauldron hot tub and a waterpark" },
  { chapter: "Chapter One", word: "twirly", pos: "형용사", meaning: "빙글빙글 도는", example: "with a twirly witch's hat slide! I couldn't wait!" },
  { chapter: "Chapter One", word: "skidded", pos: "동사", meaning: "미끄러지듯 들어갔다", example: "I skidded into my bedroom and looked around for my fairy wand." },
  { chapter: "Chapter One", word: "magic up", pos: "동사(구)", meaning: "마법으로 만들어내다", example: "I could use it to magic up some fairy food to eat while we were away." },
  { chapter: "Chapter One", word: "way nicer", pos: "표현", meaning: "훨씬 더 좋은", example: "Fairy food is way nicer than witch food." },
  { chapter: "Chapter One", word: "wistfully", pos: "부사", meaning: "아쉬운 듯이, 그리운 듯이", example: "As I did so, I stared wistfully at my..." },
  { chapter: "Chapter One", word: "travelling potion kit", pos: "명사(구)", meaning: "휴대용 물약 키트", example: "witch's travelling potion kit which was arranged proudly on my bedside table." },
  { chapter: "Chapter One", word: "arranged proudly", pos: "표현", meaning: "자랑스럽게 정돈되어", example: "arranged proudly on my bedside table." },
  { chapter: "Chapter One", word: "mischief", pos: "명사", meaning: "장난", example: "'It always gets you into mischief, Mirabelle,' Mum had said." },
  { chapter: "Chapter One", word: "would like a break", pos: "표현", meaning: "휴식을 갖고 싶다", example: "'Dad and I would like a break this holiday.'" },
  { chapter: "Chapter One", word: "unpredictable", pos: "형용사", meaning: "예측할 수 없는", example: "'It's too unpredictable.'" },
  { chapter: "Chapter One", word: "And I really did mean it.", pos: "문장", meaning: "그리고 나는 정말 진심이었다.", example: "And I really did mean it." },
  { chapter: "Chapter One", word: "what harm could it do", pos: "관용구", meaning: "그게 무슨 문제가 될까", example: "What harm could it do to just have both of them with me?" },
  { chapter: "Chapter One", word: "making a great show of", pos: "관용구", meaning: "~인 척 크게 티를 내다", example: "making a great show of unzipping my suitcase to put it inside" },
  { chapter: "Chapter One", word: "absorb", pos: "동사", meaning: "흡수하다, 만끽하다", example: "I can't wait to get to that lovely forest and absorb all the beautiful nature!" },
  { chapter: "Chapter One", word: "hooting and tooting", pos: "표현(의성어)", meaning: "빵빵거리며", example: "that cars line up behind us, hooting and tooting." },
  { chapter: "Chapter One", word: "grumbled", pos: "동사", meaning: "투덜거렸다", example: "'You should have let me drive!' grumbled Mum" },
  { chapter: "Chapter One", word: "applied a layer of", pos: "동사(구)", meaning: "~을 한 겹 발랐다", example: "applied a layer of dark purple lipstick." },
  { chapter: "Chapter One", word: "daredevil", pos: "명사", meaning: "무모한 사람", example: "'You drive like a daredevil!'" },
  { chapter: "Chapter One", word: "secretly felt glad", pos: "표현", meaning: "몰래 기뻐했다", example: "Mum huffed but I secretly felt glad that Dad was driving us rather than Mum" },
  { chapter: "Chapter One", word: "at a snail's pace", pos: "관용구", meaning: "아주 느린 속도로", example: "even if we were travelling at a snail's pace." },
  { chapter: "Chapter One", word: "winding roads", pos: "명사(구)", meaning: "구불구불한 길", example: "along some narrow winding roads." },
  { chapter: "Chapter One", word: "hilly", pos: "형용사", meaning: "언덕이 많은", example: "The landscape had become quite hilly" },
  { chapter: "Chapter One", word: "distance", pos: "명사", meaning: "(먼) 거리, 저 멀리", example: "I could see mountains in the distance." },
  { chapter: "Chapter One", word: "magnificent", pos: "형용사", meaning: "웅장한", example: "'Ah!' said Dad. 'Isn't nature magnificent!'" },
  { chapter: "Chapter One", word: "totally absorbed", pos: "표현", meaning: "완전히 몰두한", example: "totally absorbed in his book of Wizard's Wordsearches." },
  { chapter: "Chapter One", word: "Wordsearches", pos: "명사", meaning: "낱말찾기 퍼즐", example: "totally absorbed in his book of Wizard's Wordsearches." },
  { chapter: "Chapter One", word: "atmosphere", pos: "명사", meaning: "분위기", example: "the atmosphere became a little dark and creepy." },
  { chapter: "Chapter One", word: "creepy", pos: "형용사", meaning: "으스스한", example: "the atmosphere became a little dark and creepy." },
  { chapter: "Chapter One", word: "rubbing her hands together with glee", pos: "표현", meaning: "신나서 두 손을 비비다", example: "said Mum, rubbing her hands together with glee." },
  { chapter: "Chapter One", word: "witchy", pos: "형용사", meaning: "마녀 같은", example: "'This feels witchy!'" },
  { chapter: "Chapter One", word: "cackling", pos: "명사", meaning: "낄낄거리는 웃음(소리)", example: "the faint sound of cackling, and a thin trail of smoke" },
  { chapter: "Chapter One", word: "wound up", pos: "동사(구)", meaning: "위로 올라갔다(감겨 올라갔다)", example: "a thin trail of smoke wound up into the sky from somewhere nearby." },
  { chapter: "Chapter One", word: "spindly", pos: "형용사", meaning: "가늘고 길쭉한", example: "The trees look rather dark and spindly to me." },
  { chapter: "Chapter One", word: "heave", pos: "동사", meaning: "(무거운 것을) 힘겹게 들어올리다", example: "She opened the car boot and began to heave our suitcases out" },
  { chapter: "Chapter One", word: "breathed deeply", pos: "표현", meaning: "깊게 숨을 쉬었다", example: "Dad closed his eyes and breathed deeply." },
  { chapter: "Chapter One", word: "under his breath", pos: "관용구", meaning: "소곤소곤, 작은 목소리로", example: "he kept whispering under his breath. 'All nature is beautiful.'" },
  { chapter: "Chapter One", word: "slamming", pos: "동사", meaning: "쾅 닫다", example: "said Mum, slamming the boot of the car shut again." },

  // ===== Chapter Two =====
  { chapter: "Chapter Two", word: "marvelling at", pos: "동사(구)", meaning: "감탄하며 바라보다", example: "I gazed upwards marvelling at the beautiful treehouses" },
  { chapter: "Chapter Two", word: "deckchairs up high on wooden platforms", pos: "표현", meaning: "높은 나무 데크 위 접이식 의자에", example: "I could see witches and wizards sitting in deckchairs up high on wooden platforms," },
  { chapter: "Chapter Two", word: "cackling", pos: "명사", meaning: "낄낄거리는 웃음(소리)", example: "sipping fancy drinks and cackling." },
  { chapter: "Chapter Two", word: "a spiral of", pos: "표현", meaning: "나선형의", example: "with a spiral of wooden steps running all the way up the trunk." },
  { chapter: "Chapter Two", word: "cauldron-shaped hot tub", pos: "명사(구)", meaning: "가마솥 모양의 온수 욕조", example: "Outside on the deck was the big cauldron-shaped hot tub." },
  { chapter: "Chapter Two", word: "disgruntled", pos: "형용사", meaning: "불만스러운, 언짢은", example: "Wilbur looked disgruntled and I found myself feeling surprisingly hurt." },
  { chapter: "Chapter Two", word: "found myself feeling surprisingly hurt", pos: "표현", meaning: "(나 스스로도) 뜻밖에 속상해졌다", example: "Wilbur looked disgruntled and I found myself feeling surprisingly hurt." },
  { chapter: "Chapter Two", word: "get on each other's nerves", pos: "관용구", meaning: "서로 신경을 건드리다", example: "I know we sometimes get on each other's nerves" },
  { chapter: "Chapter Two", word: "settling in", pos: "동사(구)", meaning: "자리를 잡다, 적응하다", example: "We spent the next hour unpacking and settling in to our treehouse." },
  { chapter: "Chapter Two", word: "declared", pos: "동사", meaning: "선언하듯 말했다", example: "I declared, changing into my swimming costume as fast as I could." },
  { chapter: "Chapter Two", word: "cauldron", pos: "명사", meaning: "(마녀들이 쓰는) 가마솥", example: "I ran out onto the balcony and jumped into the giant cauldron with a splash!" },
  { chapter: "Chapter Two", word: "panted", pos: "동사", meaning: "헐떡였다", example: "'Ooh!' I panted." },
  { chapter: "Chapter Two", word: "gingerly", pos: "부사", meaning: "조심조심", example: "said Dad, sticking his toe in gingerly." },
  { chapter: "Chapter Two", word: "ease yourself in", pos: "관용구", meaning: "조심스럽게 몸을 담그다", example: "'You have to ease yourself in, Mirabelle. Ease yourself in.'" },
  { chapter: "Chapter Two", word: "jellied insects", pos: "명사(구)", meaning: "젤리로 된 곤충 과자", example: "Mum had brought out a platter of jellied insects" },
  { chapter: "Chapter Two", word: "was popping them into", pos: "표현", meaning: "(음식을) 쏙쏙 집어넣고 있었다", example: "she was popping them into her mouth like sweets." },
  { chapter: "Chapter Two", word: "wrinkled his back at me", pos: "표현", meaning: "나를 향해 코를(등을) 찡그렸다", example: "I wrinkled my nose at Wilbur and he wrinkled his back at me." },
  { chapter: "Chapter Two", word: "afterwards", pos: "부사", meaning: "그 후에, 나중에", example: "And then we can have dinner afterwards!" },
  { chapter: "Chapter Two", word: "for just such an occasion", pos: "표현", meaning: "바로 이런 때를 위해", example: "I packed some honey sandwiches for just such an occasion." },
  { chapter: "Chapter Two", word: "milling about", pos: "동사(구)", meaning: "(사람들이) 어슬렁거리며 모여 있다", example: "There were lots of other witch and wizard families milling about the Great Hall." },
  { chapter: "Chapter Two", word: "dragon trekking", pos: "명사(구)", meaning: "드래곤 트레킹(용을 타고 하는 탐험 활동)", example: "'I want to go dragon trekking!' said another voice next to us." },
  { chapter: "Chapter Two", word: "spirally curls", pos: "명사(구)", meaning: "나선형 곱슬머리", example: "She had spirally curls and a cheeky expression on her face." },
  { chapter: "Chapter Two", word: "cheeky expression", pos: "명사(구)", meaning: "장난기 있는(까부는) 표정", example: "and a cheeky expression on her face." },
  { chapter: "Chapter Two", word: "mischief", pos: "명사", meaning: "장난", example: "'Last time we went dragon trekking you got up to all kinds of mischief.'" },
  { chapter: "Chapter Two", word: "a flicker of", pos: "표현", meaning: "살짝 스치는, 언뜻 비치는", example: "A flicker of mischief passed between us." },

  // ===== Chapter Three =====
  { chapter: "Chapter Three", word: "conversation", pos: "명사", meaning: "대화", example: "It wasn't long before Mum and Dad were deep in conversation with Beatrix's parents" },
  { chapter: "Chapter Three", word: "impressed", pos: "형용사", meaning: "감명받은, 인상 깊어하는", example: "she didn't look quite as impressed as I thought she would be." },
  { chapter: "Chapter Three", word: "furious", pos: "형용사", meaning: "몹시 화난", example: "'She was furious!'" },
  { chapter: "Chapter Three", word: "That reminds me", pos: "표현", meaning: "그러고 보니 생각난다", example: "'That reminds me of the time that I made everyone in my classroom go bald.'" },
  { chapter: "Chapter Three", word: "gobsmacked", pos: "형용사", meaning: "어안이 벙벙한", example: "I stared at Beatrix, gobsmacked, and she nodded" },
  { chapter: "Chapter Three", word: "as naughty as", pos: "표현", meaning: "~만큼 짓궂은", example: "I had never met anyone as naughty as Beatrix before." },
  { chapter: "Chapter Three", word: "absolutely no mischief", pos: "표현", meaning: "전혀 장난치지 않기", example: "And I had promised Mum and Dad that there would be absolutely no mischief this holiday." },
  { chapter: "Chapter Three", word: "snuggled down", pos: "동사(구)", meaning: "이불 속으로 파고들다", example: "'I can't wait!' said Wilbur as he snuggled down into bed." },

  // ===== Chapter Four =====
  { chapter: "Chapter Four", word: "got dressed", pos: "동사(구)", meaning: "옷을 입었다", example: "I hurriedly got dressed, and then went out onto the deck" },
  { chapter: "Chapter Four", word: "felt my cheeks", pos: "표현", meaning: "뺨이 빨개지는 것을 느꼈다", example: "I felt my cheeks turn a bit pink." },
  { chapter: "Chapter Four", word: "allowed", pos: "형용사", meaning: "허락된", example: "'I'm allowed to bring my wizards things,' said Wilbur" },
  { chapter: "Chapter Four", word: "sensible", pos: "형용사", meaning: "신중한, 분별 있는", example: "'because I'm sensible with them!'" },
  { chapter: "Chapter Four", word: "immediately cross", pos: "표현", meaning: "곧바로 화가 난", example: "He looked so smug that I felt immediately cross." },
  { chapter: "Chapter Four", word: "huffed", pos: "동사", meaning: "씩씩거리며 말했다", example: "'Just don't tell Mum and Dad,' I huffed, and stomped out of the room" },
  { chapter: "Chapter Four", word: "approvingly", pos: "부사", meaning: "만족스러운 듯이, 흡족하게", example: "'Very good, Mirabelle!' said Dad approvingly" },
  { chapter: "Chapter Four", word: "binoculars", pos: "명사", meaning: "쌍안경", example: "had a pair of binoculars hanging round her neck." },
  { chapter: "Chapter Four", word: "beckoned for", pos: "동사(구)", meaning: "오라고 손짓했다", example: "the tour guide suddenly appeared and beckoned for us all to follow him into the forest." },
  { chapter: "Chapter Four", word: "snoozing and crunching", pos: "표현", meaning: "졸면서 아작아작 씹어먹는", example: "there were lots of dragons happily snoozing and crunching on charcoal." },
  { chapter: "Chapter Four", word: "reins", pos: "명사", meaning: "고삐", example: "put a saddle and reins onto our chosen dragons" },
  { chapter: "Chapter Four", word: "regulations", pos: "명사", meaning: "규정, 규칙", example: "It's against health and safety regulations." },
  { chapter: "Chapter Four", word: "Violet fluttered", pos: "표현", meaning: "바이올렛이 파닥거렸다", example: "Violet fluttered by my shoulder." },
  { chapter: "Chapter Four", word: "binoculars", pos: "명사", meaning: "쌍안경", example: "I saw Beatrix peer through her binoculars." },
  { chapter: "Chapter Four", word: "The effect was immediate", pos: "표현", meaning: "효과는 즉각적이었다", example: "The effect was immediate." },
  { chapter: "Chapter Four", word: "cantering forwards, overtaking", pos: "표현", meaning: "앞으로 달려나가며 추월하는", example: "It began cantering forwards, overtaking Wilbur and Dad and all the dragons in the line." },
  { chapter: "Chapter Four", word: "hunched down", pos: "동사(구)", meaning: "몸을 웅크렸다", example: "I gripped onto the reins and hunched down" },
  { chapter: "Chapter Four", word: "shrieking in delight", pos: "표현", meaning: "기뻐서 비명을 지르며", example: "just as Beatrix came whooshing past, shrieking in delight." },
  { chapter: "Chapter Four", word: "for dear life", pos: "관용구", meaning: "필사적으로", example: "I held onto its neck for dear life." },
  { chapter: "Chapter Four", word: "shrieked", pos: "동사", meaning: "비명을 질렀다", example: "'Heeeelp!' I shrieked." },
  { chapter: "Chapter Four", word: "including", pos: "전치사", meaning: "~을 포함해서", example: "Everyone, including Beatrix, had now stopped and was staring up at me in horror." },
  { chapter: "Chapter Four", word: "sorrowfully", pos: "부사", meaning: "슬프게, 후회하는 듯이", example: "I nodded my head sorrowfully." },
  { chapter: "Chapter Four", word: "dragged me back", pos: "동사(구)", meaning: "나를 억지로 끌고 갔다", example: "She took me by the arm and dragged me back through the forest" },
  { chapter: "Chapter Four", word: "fumed", pos: "동사", meaning: "분통을 터뜨리며 말했다", example: "'No we can't!' fumed Mum." },
  { chapter: "Chapter Four", word: "very bad mood", pos: "표현", meaning: "매우 안 좋은 기분", example: "Back at the treehouse Wilbur was in a very bad mood." },
  { chapter: "Chapter Four", word: "absorbed in", pos: "표현", meaning: "~에 몰두한", example: "sat on his bed, absorbed in his book of Wizards Wordsearches." },
  { chapter: "Chapter Four", word: "trekking incident", pos: "명사(구)", meaning: "트레킹 사건", example: "why Mum and Dad thought that the dragon trekking incident was all my fault." },
  { chapter: "Chapter Four", word: "things were my fault", pos: "표현", meaning: "늘 내 잘못이었다", example: "It was because usually things were my fault." },

  // ===== Chapter Five =====
  { chapter: "Chapter Five", word: "unenthusiastically", pos: "부사", meaning: "내키지 않는 듯이, 시큰둥하게", example: "'Hi, Beatrix,' I said unenthusiastically." },
  { chapter: "Chapter Five", word: "whispery voice", pos: "표현", meaning: "속삭이는 듯한 목소리", example: "she said again in a more whispery voice this time." },
  { chapter: "Chapter Five", word: "tuck in", pos: "동사(구)", meaning: "(음식을) 맛있게 먹기 시작하다", example: "We all started to tuck in." },
  { chapter: "Chapter Five", word: "flick", pos: "동사", meaning: "휙 튀기다, 튕기다", example: "Suddenly, I saw something flick across the table and over my plate," },
  { chapter: "Chapter Five", word: "ARGHHHH", pos: "표현", meaning: "으악! (비명 소리)", example: "'ARGHHHH!' screamed Wilbur, leaping out of his chair" },
  { chapter: "Chapter Five", word: "squirming pile of worms", pos: "표현", meaning: "꿈틀거리는 벌레 더미", example: "spaghetti which had turned into a squirming pile of worms." },
  { chapter: "Chapter Five", word: "confiscated", pos: "동사(과거분사)", meaning: "압수된, 몰수된", example: "'You were just getting me back for telling Mum and Dad your potion kit's been confiscated!'" },
  { chapter: "Chapter Five", word: "grabbed", pos: "동사", meaning: "움켜쥐었다", example: "the worms landed all over my hair, slimy and squirmy and disgusting. I grabbed" },
  { chapter: "Chapter Five", word: "glittering with delight", pos: "표현", meaning: "기뻐서 반짝이는", example: "said Beatrix, looking up, her eyes glittering with delight." },
  { chapter: "Chapter Five", word: "explode", pos: "동사", meaning: "폭발하다", example: "Wilbur looked so cross that I thought he might explode." },
  { chapter: "Chapter Five", word: "lobbed", pos: "동사", meaning: "휙 던졌다", example: "Wilbur picked up his bread roll and lobbed it into my face." },
  { chapter: "Chapter Five", word: "blazing", pos: "형용사", meaning: "이글거리는, 활활 타는", example: "'BOTH OF YOU STOP IT THIS INSTANT!' shouted Mum. Her eyes were blazing." },
  { chapter: "Chapter Five", word: "sat down heavily", pos: "표현", meaning: "털썩 주저앉았다", example: "I sat down heavily on my bed and clutched Violet to my chest." },
  { chapter: "Chapter Five", word: "clutched", pos: "동사", meaning: "꽉 붙잡았다, 움켜쥐었다", example: "I sat down heavily on my bed and clutched Violet to my chest." },
  { chapter: "Chapter Five", word: "disbelievingly", pos: "부사", meaning: "믿기지 않는 듯이", example: "Wilbur turned round. He narrowed his eyes disbelievingly." },
  { chapter: "Chapter Five", word: "flicked it", pos: "동사(구)", meaning: "휙 튕겼다", example: "Then during dinner I think she flicked it onto your plate." },
  { chapter: "Chapter Five", word: "looked slightly less angry", pos: "표현", meaning: "조금 덜 화나 보였다", example: "'I don't know,' said Wilbur, but he looked slightly less angry." },
  { chapter: "Chapter Five", word: "naughtier than you", pos: "표현", meaning: "너보다 더 짓궂은", example: "'If you're telling the truth, that means Beatrix is even naughtier than you!'" },
  { chapter: "Chapter Five", word: "follow me around", pos: "동사(구)", meaning: "나를 졸졸 따라다니다", example: "Trouble just seems to follow me around." },
  { chapter: "Chapter Five", word: "mischief", pos: "명사", meaning: "장난", example: "'You need to tell Beatrix that you don't want any more tricks or mischief!' said Wilbur." },
  { chapter: "Chapter Five", word: "rather embarrassed", pos: "표현", meaning: "다소 부끄러워하는", example: "He's rather embarrassed about his fairy heritage." },
  { chapter: "Chapter Five", word: "with pudding", pos: "표현", meaning: "디저트로 시작해서", example: "'I know! Let's start with pudding.'" },
  { chapter: "Chapter Five", word: "suspiciously", pos: "부사", meaning: "미심쩍은 듯이, 의심스럽게", example: "Wilbur picked it up and peered at it suspiciously for a moment." },
  { chapter: "Chapter Five", word: "similar", pos: "형용사", meaning: "비슷한", example: "Then he began to magic up something similar for myself," },

  // ===== Chapter Six =====
  { chapter: "Chapter Six", word: "slunk", pos: "동사", meaning: "슬금슬금 걸어갔다", example: "came sheepishly out of our bedroom and slunk towards the breakfast table." },
  { chapter: "Chapter Six", word: "dressing gown", pos: "명사(구)", meaning: "실내 가운", example: "her black silk dressing gown." },
  { chapter: "Chapter Six", word: "absolutely no mischief", pos: "표현", meaning: "전혀 장난치지 않기", example: "'Let's try and have absolutely no mischief today shall we?'" },
  { chapter: "Chapter Six", word: "bubbling rapids", pos: "표현", meaning: "부글부글 끓는 급류", example: "There were some witchy bubbling rapids, a tube slide" },
  { chapter: "Chapter Six", word: "inflatable", pos: "형용사", meaning: "공기를 넣어 부풀리는", example: "loads of inflatable black cats that you could ride on." },
  { chapter: "Chapter Six", word: "firmly", pos: "부사", meaning: "단호하게", example: "'I didn't need you to do that for me, Beatrix,' I said firmly." },
  { chapter: "Chapter Six", word: "shrieking and laughing", pos: "표현", meaning: "비명을 지르며 웃는", example: "we went, shrieking and laughing until we landed" },
  { chapter: "Chapter Six", word: "cauldron-shaped pool", pos: "명사(구)", meaning: "가마솥 모양의 수영장", example: "in a bubbling cauldron-shaped pool at the bottom with a big SPLASH." },
  { chapter: "Chapter Six", word: "managed", pos: "동사", meaning: "해냈다, 간신히 해내다", example: "I managed to swim to the edge of the cauldron and grab onto the side," },
  { chapter: "Chapter Six", word: "fiercer", pos: "형용사", meaning: "더 사나운, 더 거센", example: "The water coming off the bottom of the slide looked fiercer than before too!" },
  { chapter: "Chapter Six", word: "really gushing", pos: "표현", meaning: "세차게 쏟아지는", example: "really gushing into the now swirling whirling whirlpool." },
  { chapter: "Chapter Six", word: "grip onto", pos: "동사(구)", meaning: "꽉 붙잡다", example: "I continued to grip onto the side, watching and waiting for Beatrix" },
  { chapter: "Chapter Six", word: "onto the edge of", pos: "표현", meaning: "~의 가장자리로", example: "'Beatrix!' I shrieked. Still holding onto the edge of the cauldron with one hand" },
  { chapter: "Chapter Six", word: "dragged her up", pos: "동사(구)", meaning: "그녀를 끌어올렸다", example: "caught Beatrix's arm and dragged her up, coughing and spluttering." },
  { chapter: "Chapter Six", word: "coughing and spluttering", pos: "표현", meaning: "기침하며 캑캑거리는", example: "caught Beatrix's arm and dragged her up, coughing and spluttering." },
  { chapter: "Chapter Six", word: "extremely dangerous", pos: "표현", meaning: "극도로 위험한", example: "which now looked extremely dangerous with the torrents of water gushing off it." },
  { chapter: "Chapter Six", word: "a bit shifty", pos: "표현", meaning: "약간 수상쩍은", example: "Beatrix looked a bit shifty." },
  { chapter: "Chapter Six", word: "undo it", pos: "동사(구)", meaning: "그것을 원상태로 되돌리다", example: "'But I didn't bring any potion to undo it!' said Beatrix looking worried." },
  { chapter: "Chapter Six", word: "reach in", pos: "동사(구)", meaning: "손을 뻗어 안으로 넣다", example: "you'll have to reach in and get them out!'" },
  { chapter: "Chapter Six", word: "kneeled down and scrabbled underneath", pos: "표현", meaning: "무릎을 꿇고 아래를 더듬거리며 뒤졌다", example: "I kneeled down and scrabbled underneath the chair, pulling out my towel" },
  { chapter: "Chapter Six", word: "unrolling it", pos: "동사(구)", meaning: "그것을 펼쳤다", example: "pulling out my towel and unrolling it." },
  { chapter: "Chapter Six", word: "breathlessly", pos: "부사", meaning: "숨이 차서, 헐떡이며", example: "I said breathlessly. 'Just trust me! It's an emergency!'" },
  { chapter: "Chapter Six", word: "emergency", pos: "명사", meaning: "비상 상황, 응급 상황", example: "'Just trust me! It's an emergency!'" },
  { chapter: "Chapter Six", word: "visualising", pos: "동사", meaning: "머릿속으로 그려보다, 상상하다", example: "I waved my fairy wand, visualising exactly what I wanted to happen." },
  { chapter: "Chapter Six", word: "MIRABELLE STARSPELL", pos: "표현", meaning: "(화가 나서) 이름을 풀네임으로 부름", example: "'MIRABELLE STARSPELL!' she began." },
  { chapter: "Chapter Six", word: "just fixing it", pos: "표현", meaning: "그냥 고치고 있었을 뿐인", example: "'I didn't do anything!' I said. 'I was just fixing it!'" },
  { chapter: "Chapter Six", word: "suspiciously", pos: "부사", meaning: "의심스러운 듯이", example: "Wilbur stared suspiciously at Beatrix" },
  { chapter: "Chapter Six", word: "un-Wilburish thing", pos: "표현", meaning: "윌버답지 않은 행동", example: "and then he did a very un-Wilburish thing." },
  { chapter: "Chapter Six", word: "trying", pos: "동사", meaning: "노력하고 있는", example: "'I'm trying to be good this holiday.'" },
];
