// Mirabelle in Double Trouble 단어장 데이터
// 각 항목: chapter(챕터), word(단어/표현), pos(품사), meaning(뜻), example(본문 예문)
// 아이가 책에 직접 밑줄 그은 단어·숙어·문장만 정리했습니다.
const MIRABELLE_VOCAB_DATA = [
  // ===== Chapter One =====
  { chapter: "Chapter One", word: "forgot", pos: "동사", meaning: "잊어버렸다", example: "'Er . . . I think I forgot,' I said." },
  { chapter: "Chapter One", word: "more often", pos: "부사(구)", meaning: "더 자주", example: "trying to get me to use my wand more often, but the truth is that I prefer to use witch magic like Mum!" },
  { chapter: "Chapter One", word: "witch", pos: "명사", meaning: "마녀", example: "the truth is that I prefer to use witch magic like Mum!" },
  { chapter: "Chapter One", word: "technically", pos: "부사", meaning: "엄밀히 말하면", example: "technically half fairy too, along with my brother, Wilbur." },
  { chapter: "Chapter One", word: "fetch", pos: "동사", meaning: "가지러 가다, 가져오다", example: "'There's still time to go and fetch it,' said Dad." },
  { chapter: "Chapter One", word: "glancing", pos: "동사", meaning: "흘깃 보다", example: "said Dad, glancing at his watch." },
  { chapter: "Chapter One", word: "while you're at it", pos: "관용구", meaning: "하는 김에", example: "'And while you're at it you can tell Mum to hurry up!'" },
  { chapter: "Chapter One", word: "own", pos: "동사", meaning: "소유하다", example: "My mum and dad own their own beauty business" },
  { chapter: "Chapter One", word: "beauty", pos: "명사", meaning: "아름다움", example: "own their own beauty business concocting organic face creams" },
  { chapter: "Chapter One", word: "concocting", pos: "동사", meaning: "(여러 재료를 섞어) 만들어내다", example: "business concocting organic face creams, perfumes, and lipsticks." },
  { chapter: "Chapter One", word: "turret", pos: "명사", meaning: "(작은) 탑", example: "Mum can spend all day up in her witch turret experimenting" },
  { chapter: "Chapter One", word: "ingredients", pos: "명사", meaning: "재료", example: "experimenting with ingredients and sometimes it's hard" },
  { chapter: "Chapter One", word: "tear her away from work", pos: "관용구", meaning: "그녀를 억지로 일에서 떼어놓다", example: "sometimes it's hard to tear her away from work!" },
  { chapter: "Chapter One", word: "fizzle", pos: "명사", meaning: "자글거리는 느낌, 짜릿함", example: "I felt a fizzle of excitement in my tummy." },
  { chapter: "Chapter One", word: "all-inclusive", pos: "형용사", meaning: "모든 것이 포함된", example: "at an all-inclusive witch resort in the mountains." },
  { chapter: "Chapter One", word: "cauldron", pos: "명사", meaning: "(마녀들이 쓰는) 가마솥", example: "to be a bubbling cauldron hot tub and a waterpark" },
  { chapter: "Chapter One", word: "twirly", pos: "형용사", meaning: "빙글빙글 도는", example: "with a twirly witch's hat slide! I couldn't wait!" },
  { chapter: "Chapter One", word: "skidded", pos: "동사", meaning: "미끄러지듯 들어갔다", example: "I skidded into my bedroom and looked around for my fairy wand." },
  { chapter: "Chapter One", word: "magic up", pos: "동사(구)", meaning: "마법으로 만들어내다", example: "I could use it to magic up some fairy food to eat while we were away." },
  { chapter: "Chapter One", word: "way nicer", pos: "표현", meaning: "훨씬 더 좋은", example: "Fairy food is way nicer than witch food." },
  { chapter: "Chapter One", word: "wistfully", pos: "부사", meaning: "아쉬운 듯이, 그리운 듯이", example: "As I did so, I stared wistfully at my..." },
  { chapter: "Chapter One", word: "travelling potion kit", pos: "명사(구)", meaning: "휴대용 물약 키트", example: "witch's travelling potion kit which was arranged proudly on my bedside table." },
  { chapter: "Chapter One", word: "arranged proudly", pos: "표현", meaning: "자랑스럽게 정돈되어", example: "arranged proudly on my bedside table." },
  { chapter: "Chapter One", word: "mischief", pos: "명사", meaning: "장난", example: "'It always gets you into mischief, Mirabelle,' Mum had said." },
  { chapter: "Chapter One", word: "would like a break", pos: "표현", meaning: "휴식을 갖고 싶다", example: "'Dad and I would like a break this holiday.'" },
  { chapter: "Chapter One", word: "unpredictable", pos: "형용사", meaning: "예측할 수 없는", example: "'It's too unpredictable.'" },
  { chapter: "Chapter One", word: "And I really did mean it.", pos: "문장", meaning: "그리고 나는 정말 진심이었다.", example: "And I really did mean it." },
  { chapter: "Chapter One", word: "what harm could it do", pos: "관용구", meaning: "그게 무슨 문제가 될까", example: "What harm could it do to just have both of them with me?" },
  { chapter: "Chapter One", word: "making a great show of", pos: "관용구", meaning: "~인 척 크게 티를 내다", example: "making a great show of unzipping my suitcase to put it inside" },
  { chapter: "Chapter One", word: "absorb", pos: "동사", meaning: "흡수하다, 만끽하다", example: "I can't wait to get to that lovely forest and absorb all the beautiful nature!" },
  { chapter: "Chapter One", word: "hooting and tooting", pos: "표현(의성어)", meaning: "빵빵거리며", example: "that cars line up behind us, hooting and tooting." },
  { chapter: "Chapter One", word: "grumbled", pos: "동사", meaning: "투덜거렸다", example: "'You should have let me drive!' grumbled Mum" },
  { chapter: "Chapter One", word: "applied a layer of", pos: "동사(구)", meaning: "~을 한 겹 발랐다", example: "applied a layer of dark purple lipstick." },
  { chapter: "Chapter One", word: "daredevil", pos: "명사", meaning: "무모한 사람", example: "'You drive like a daredevil!'" },
  { chapter: "Chapter One", word: "secretly felt glad", pos: "표현", meaning: "몰래 기뻐했다", example: "Mum huffed but I secretly felt glad that Dad was driving us rather than Mum" },
  { chapter: "Chapter One", word: "at a snail's pace", pos: "관용구", meaning: "아주 느린 속도로", example: "even if we were travelling at a snail's pace." },
  { chapter: "Chapter One", word: "winding roads", pos: "명사(구)", meaning: "구불구불한 길", example: "along some narrow winding roads." },
  { chapter: "Chapter One", word: "hilly", pos: "형용사", meaning: "언덕이 많은", example: "The landscape had become quite hilly" },
  { chapter: "Chapter One", word: "distance", pos: "명사", meaning: "(먼) 거리, 저 멀리", example: "I could see mountains in the distance." },
  { chapter: "Chapter One", word: "magnificent", pos: "형용사", meaning: "웅장한", example: "'Ah!' said Dad. 'Isn't nature magnificent!'" },
  { chapter: "Chapter One", word: "totally absorbed", pos: "표현", meaning: "완전히 몰두한", example: "totally absorbed in his book of Wizard's Wordsearches." },
  { chapter: "Chapter One", word: "Wordsearches", pos: "명사", meaning: "낱말찾기 퍼즐", example: "totally absorbed in his book of Wizard's Wordsearches." },
  { chapter: "Chapter One", word: "atmosphere", pos: "명사", meaning: "분위기", example: "the atmosphere became a little dark and creepy." },
  { chapter: "Chapter One", word: "creepy", pos: "형용사", meaning: "으스스한", example: "the atmosphere became a little dark and creepy." },
  { chapter: "Chapter One", word: "rubbing her hands together with glee", pos: "표현", meaning: "신나서 두 손을 비비다", example: "said Mum, rubbing her hands together with glee." },
  { chapter: "Chapter One", word: "witchy", pos: "형용사", meaning: "마녀 같은", example: "'This feels witchy!'" },
  { chapter: "Chapter One", word: "cackling", pos: "명사", meaning: "낄낄거리는 웃음(소리)", example: "the faint sound of cackling, and a thin trail of smoke" },
  { chapter: "Chapter One", word: "wound up", pos: "동사(구)", meaning: "위로 올라갔다(감겨 올라갔다)", example: "a thin trail of smoke wound up into the sky from somewhere nearby." },
  { chapter: "Chapter One", word: "spindly", pos: "형용사", meaning: "가늘고 길쭉한", example: "The trees look rather dark and spindly to me." },
  { chapter: "Chapter One", word: "heave", pos: "동사", meaning: "(무거운 것을) 힘겹게 들어올리다", example: "She opened the car boot and began to heave our suitcases out" },
  { chapter: "Chapter One", word: "breathed deeply", pos: "표현", meaning: "깊게 숨을 쉬었다", example: "Dad closed his eyes and breathed deeply." },
  { chapter: "Chapter One", word: "under his breath", pos: "관용구", meaning: "소곤소곤, 작은 목소리로", example: "he kept whispering under his breath. 'All nature is beautiful.'" },
  { chapter: "Chapter One", word: "slamming", pos: "동사", meaning: "쾅 닫다", example: "said Mum, slamming the boot of the car shut again." },
];
